### ISSUE TITLE
Problem loader tabulizer Windows 10/ rJava class loaders

### ISSUE THREAD

**Issue by maryse-2021** [ropensci/tabulapdf#135]
Please specify whether your issue is about:

 - [ ] a possible bug
 - [X ] a question about package functionality
 - [ ] a suggested code or documentation change, improvement to the code, or feature request

Put your code here:

Hi Leeper.
Could you help me with the problem I have in installing tabulizer.
I correctly installed RJava library. I have rJava 0.9-13 2020-07-06 [1] CRAN (R 4.0.3).
I downloaded: jdk-11.0.10_windows-x64
I get this error message:
library(tabulizer)
Erreur : package or namespace load failed for ‘tabulizer’:
.onLoad a échoué dans loadNamespace() pour 'tabulizerjars', détails :
appel : .jinit()
erreur : Unable to create a Java class loader.
I get also message error when I try to install Tabulizerjars library
WARNING: Initial Java 12 release has broken JNI support and does NOT work. Use stable Java 11 (or watch for 12u if avaiable).
ERROR: Java exception occurred during rJava bootstrap - see stderr for Java stack trace.
Exception in thread "main" java.lang.NoClassDefFoundError: RJavaClassLoader
Caused by: java.lang.ClassNotFoundException: RJavaClassLoader
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
WARNING: Initial Java 12 release has broken JNI support and does NOT work. Use stable Java 11 (or watch for 12u if avaiable).
ERROR: Java exception occurred during rJava bootstrap - see stderr for Java stack trace.
Exception in thread "main" java.lang.NullPointerException
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:290)
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280)
at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198)
at java.base/java.lang.reflect.Method.setAccessible(Method.java:192)
Erreur : package or namespace load failed for ‘tabulizerjars’:
.onLoad a échoué dans loadNamespace() pour 'tabulizerjars', détails :
appel : .jcall("RJavaTools", "Z", "classHasField", x, name, static)
erreur : RcallMethod: cannot determine object class

## session info for your system
•	Session info ----------------------------------------------------
setting value
version R version 4.0.4 (2021-02-15)
os Windows 10 x64
system x86_64, mingw32
ui RStudio
language (EN)
collate French_Canada.1252
ctype French_Canada.1252
tz America/New_York
date 2021-03-11

```

**Comment by pachadotdev** [comment]
the current version does not use tabulizerjars and works with jdk11
